# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=1000, verbose_name='Search query')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last name')),
                ('profile_picture', models.FileField(upload_to='')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Profile description')),
                ('is_public', models.BooleanField(default=True, verbose_name='Profile is public')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last user IP')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by_users', to='users.User', verbose_name='Blocked users')),
                ('followed_users', models.ManyToManyField(blank=True, related_name='followers', to='users.User', verbose_name='Followed users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insta_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='User'),
        ),
        migrations.AlterIndexTogether(
            name='search',
            index_together=set([('user', 'query')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='search',
            order_with_respect_to='user',
        ),
    ]
