# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20161113_1055'),
        ('pictures', '0003_auto_20161113_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pictures.Picture', verbose_name='Liked picture')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Liked by user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'picture')]),
        ),
    ]
