# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20161113_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='/media/'),
        ),
    ]
